### ISSUE TITLE
Cannot insert legacy ACL for an object when uniform bucket-level access is enabled

### ISSUE THREAD

**Issue by IanVaughan** [GoogleCloudPlatform/getting-started-ruby#111]
Following https://cloud.google.com/ruby/getting-started
When attempting to save an image to a book.
The following error is logged:
```
Google::Cloud::InvalidArgumentError: invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:763:in `rescue in execute'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:760:in `execute'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:350:in `insert_file'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/bucket.rb:1515:in `create_file'
	/workspace/app/models/book.rb:141:in `upload_image'
	/workspace/app/models/book.rb:137:in `update_image'
	/workspace/app/models/book.rb:131:in `update'
	/workspace/app/controllers/books_controller.rb:44:in `update'
```

**Comment by dazuma** [comment]
Transferring this issue to GoogleCloudPlatform/ruby-docs-samples which is where this code now lives.
