### ISSUE TITLE
Web is not starting in 6-task-queueing

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/getting-started-ruby#36]
This is what I get

```
root@b75e5b6f5b9b:/app# bundle exec foreman start --formation web=1       
21:06:12 web.1          | started with pid 117
21:06:14 web.1          | config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
21:06:14 web.1          | 
21:06:14 web.1          |   * development - set it to false
21:06:14 web.1          |   * test - set it to false (unless you use a tool that preloads your test environment)
21:06:14 web.1          |   * production - set it to true
21:06:14 web.1          | 
21:06:14 web.1          | /app/config/initializers/omniauth.rb:7:in `block in <top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)
```
For some reason `config/settings.yml` is not loading.

Starting without foreman works fine:

```
root@b75e5b6f5b9b:/app# bundle exec rackup -p 8080 -E production config.ru
[2016-04-22 21:06:59] INFO  WEBrick 1.3.1
[2016-04-22 21:06:59] INFO  ruby 2.2.3 (2015-08-18) [x86_64-linux]
[2016-04-22 21:06:59] INFO  WEBrick::HTTPServer#start: pid=122 port=8080
```

**Comment by bshaffer** [comment]
Following the instructions online, I was able to run the web server using foreman. I am using the `datastore` backend. Which backend are you using?

**Comment by bshaffer** [comment]
I do receive the following error when the workers run. I will continue looking into it

```
13:26:49 worker.2       | Book lookup request (5679413765079040)
13:26:49 worker.2       | rake aborted!
13:26:49 worker.2       | NoMethodError: undefined method `find_by_id' for Book:Class
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/lib/active_job/queue_adapters/pub_sub_queue_adapter.rb:40:in `block in run_worker!'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `block (2 levels) in listen'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `each'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `block in listen'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:373:in `loop'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:373:in `listen'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/lib/active_job/queue_adapters/pub_sub_queue_adapter.rb:36:in `run_worker!'
13:26:49 worker.2       | /usr/local/google/home/betterbrent/Code/getting-started-ruby/6-task-queueing/lib/tasks/run_worker.rake:4:in `block in <top (required)>'
```

**Comment by jeffmendoza** [comment]
interesting, I'm using datastore. I was running the 'foreman start' from within the docker container that was built by container builder during the gae deploy. maybe there is a problem with the base docker image. Can you try 'gcloud preview app gen-config' and then docker build/run and see if that works?
